CONTENT   = $(shell find content -type f)
POSTS     = $(shell find posts -type f)
TEMPLATES = $(shell find templates -type f)
STATIC    = $(shell find static -type f)

all: .golbarg-build .golbarg-upload

.golbarg-build: $(CONTENT) $(POSTS) $(TEMPLATES) config.yaml
	@golbarg
	@touch .golbarg-build

.golbarg-upload: .golbarg-build $(STATIC)
	@rsync -vak --delete -e ssh site/ my-site:/path/to/htdocs
	@touch .golbarg-upload